oss-fuzz: fix patches for python (#472)

diff --git a/oss_fuzz_integration/oss-fuzz-patches.diff b/oss_fuzz_integration/oss-fuzz-patches.diff
--- a/oss_fuzz_integration/oss-fuzz-patches.diff
+++ b/oss_fuzz_integration/oss-fuzz-patches.diff
@@ -1,8 +1,8 @@
 diff --git a/infra/base-images/base-builder/Dockerfile b/infra/base-images/base-builder/Dockerfile
-index f1100247..d1eb8f42 100644
+index b082836f..a0a61bb3 100644
 --- a/infra/base-images/base-builder/Dockerfile
 +++ b/infra/base-images/base-builder/Dockerfile
-@@ -160,5 +160,8 @@ COPY cargo compile compile_afl compile_libfuzzer compile_honggfuzz \
+@@ -149,5 +149,8 @@ COPY cargo compile compile_afl compile_libfuzzer compile_honggfuzz \
  COPY llvmsymbol.diff $SRC
  COPY detect_repo.py /opt/cifuzz/
  COPY bazel.bazelrc /root/.bazelrc
@@ -12,7 +12,7 @@ index f1100247..d1eb8f42 100644
  
  CMD ["compile"]
 diff --git a/infra/base-images/base-builder/compile b/infra/base-images/base-builder/compile
-index 402c07a8..8f74d958 100755
+index 402c07a8..37f67166 100755
 --- a/infra/base-images/base-builder/compile
 +++ b/infra/base-images/base-builder/compile
 @@ -27,8 +27,8 @@ if [ "$FUZZING_LANGUAGE" = "jvm" ]; then
@@ -21,11 +21,20 @@ index 402c07a8..8f74d958 100755
    fi
 -  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "coverage" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "none" ]; then
 -    echo "ERROR: JVM projects can be fuzzed with AddressSanitizer or UndefinedBehaviorSanitizer only."
-+  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "coverage" ] && [ "$SANITIZER" != "introspector" ]; then
++  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "coverage" ]; then
 +    echo "ERROR: Python projects can be fuzzed with AddressSanitizer or UndefinedBehaviorSanitizer or Coverage only or Introspector."
      exit 1
    fi
    if [ "$ARCHITECTURE" != "x86_64" ]; then
+@@ -42,7 +42,7 @@ if [ "$FUZZING_LANGUAGE" = "python" ]; then
+     echo "ERROR: Python projects can be fuzzed with libFuzzer engine only."
+     exit 1
+   fi
+-  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "coverage" ]; then
++  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "coverage" ] && [ "$SANITIZER" != "introspector" ]; then
+     echo "ERROR: Python projects can be fuzzed with AddressSanitizer or UndefinedBehaviorSanitizer or Coverage only."
+     exit 1
+   fi
 @@ -210,33 +210,46 @@ if [ "$SANITIZER" = "introspector" ]; then
    unset CFLAGS
    apt-get install -y libjpeg-dev zlib1g-dev
@@ -122,10 +131,10 @@ index e7c7f0a3..829db7d1 100755
  if [[ $SANITIZER = *coverage* ]]; then
    cat <<EOF > coverage_wrapper.py
 diff --git a/infra/base-images/base-clang/Dockerfile b/infra/base-images/base-clang/Dockerfile
-index fcd4f953..6aa15b6f 100644
+index 343b4a50..75d81d27 100644
 --- a/infra/base-images/base-clang/Dockerfile
 +++ b/infra/base-images/base-clang/Dockerfile
-@@ -42,6 +42,8 @@ RUN apt-get update && apt-get install -y git && \
+@@ -44,6 +44,8 @@ RUN apt-get update && apt-get install -y git && \
  COPY checkout_build_install_llvm.sh /root/
  # Keep all steps in the same script to decrease the number of intermediate
  # layes in docker file.
@@ -135,7 +144,7 @@ index fcd4f953..6aa15b6f 100644
  RUN rm /root/checkout_build_install_llvm.sh
  
 diff --git a/infra/base-images/base-runner/coverage b/infra/base-images/base-runner/coverage
-index 1659ee94..fc5e682d 100755
+index 1659ee94..d55586d5 100755
 --- a/infra/base-images/base-runner/coverage
 +++ b/infra/base-images/base-runner/coverage
 @@ -303,13 +303,20 @@ elif [[ $FUZZING_LANGUAGE == "python" ]]; then
