oss-fuzz: provide patches for jvm integration (#628)
* oss-fuzz: provide necessary patches for oss-fuzz java integration

Signed-off-by: David Korczynski <david@adalogics.com>

* oss-fuzz: add jvm image to build post processing

Signed-off-by: David Korczynski <david@adalogics.com>

* oss-fuzz: jvm.patch: update to work with relevant oss-fuzz patches

Signed-off-by: David Korczynski <david@adalogics.com>

* void out runner.py jvm patches. To be further cleaned up

Signed-off-by: David Korczynski <david@adalogics.com>

* oss-fuzz: cleanup runner

Signed-off-by: David Korczynski <david@adalogics.com>

Signed-off-by: David Korczynski <david@adalogics.com>

diff --git a/oss_fuzz_integration/oss-fuzz-patches.diff b/oss_fuzz_integration/oss-fuzz-patches.diff
--- a/oss_fuzz_integration/oss-fuzz-patches.diff
+++ b/oss_fuzz_integration/oss-fuzz-patches.diff
@@ -1,8 +1,8 @@
 diff --git a/infra/base-images/base-builder/Dockerfile b/infra/base-images/base-builder/Dockerfile
-index aa954a17..c033e1c4 100644
+index 12c08499..9808589b 100644
 --- a/infra/base-images/base-builder/Dockerfile
 +++ b/infra/base-images/base-builder/Dockerfile
-@@ -160,5 +160,9 @@ COPY cargo compile compile_afl compile_libfuzzer compile_honggfuzz \
+@@ -162,5 +162,9 @@ COPY cargo compile compile_afl compile_libfuzzer compile_honggfuzz \
  COPY llvmsymbol.diff $SRC
  COPY detect_repo.py /opt/cifuzz/
  COPY bazel.bazelrc /root/.bazelrc
@@ -12,8 +12,48 @@ index aa954a17..c033e1c4 100644
 +COPY frontends /fuzz-introspector/frontends
  
  CMD ["compile"]
+diff --git a/infra/base-images/base-builder/compile b/infra/base-images/base-builder/compile
+index e82b8153..b0e3688e 100755
+--- a/infra/base-images/base-builder/compile
++++ b/infra/base-images/base-builder/compile
+@@ -16,7 +16,7 @@
+ ################################################################################
+ 
+ echo "---------------------------------------------------------------"
+-
++echo "Checking with sanitizer $SANITIZER"
+ # This is a temporary fix: fall back to LLVM14's old pass manager
+ if [ -n "${OLD_LLVMPASS-}" ]; then
+   export SANITIZER_FLAGS_introspector=$(echo $SANITIZER_FLAGS_introspector | sed -r 's/-O0/-flegacy-pass-manager/')
+@@ -27,8 +27,9 @@ if [ "$FUZZING_LANGUAGE" = "jvm" ]; then
+     echo "ERROR: JVM projects can be fuzzed with libFuzzer or tested with wycheproof engines only."
+     exit 1
+   fi
+-  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "coverage" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "none" ]; then
+-    echo "ERROR: JVM projects can be fuzzed with AddressSanitizer or UndefinedBehaviorSanitizer only."
++  if [ "$SANITIZER" != "address" ] && [ "$SANITIZER" != "coverage" ] && [ "$SANITIZER" != "undefined" ] && [ "$SANITIZER" != "none" ] && [ "$SANITIZER" != "introspector" ]; then
++    echo "$SANITIZER"
++    echo "ERROR: JVM projects can be fuzzed with AddressSanitizer or UndefinedBehaviorSanitizer or introspector only."
+     exit 1
+   fi
+   if [ "$ARCHITECTURE" != "x86_64" ]; then
+@@ -251,6 +252,14 @@ if [ "$SANITIZER" = "introspector" ]; then
+     REPORT_ARGS="$REPORT_ARGS --language=python"
+     python3 /fuzz-introspector/src/main.py report $REPORT_ARGS
+     cp -rf $SRC/inspector $OUT/inspector
++  elif [ "$FUZZING_LANGUAGE" = "jvm" ]; then
++    echo "GOING jvm route"
++    set -x
++    find $OUT/ -name "jacoco.xml" -exec cp {} $SRC/inspector/ \;
++    REPORT_ARGS="$REPORT_ARGS --target_dir=$SRC/inspector"
++    REPORT_ARGS="$REPORT_ARGS --language=jvm"
++    python3 /fuzz-introspector/src/main.py report $REPORT_ARGS
++    cp -rf $SRC/inspector $OUT/inspector
+   else
+     # C/C++
+ 
 diff --git a/infra/base-images/base-clang/Dockerfile b/infra/base-images/base-clang/Dockerfile
-index 964a10a0..1c3d686d 100644
+index a4e23350..d734662f 100644
 --- a/infra/base-images/base-clang/Dockerfile
 +++ b/infra/base-images/base-clang/Dockerfile
 @@ -45,6 +45,8 @@ RUN apt-get update && apt-get install -y git && \
@@ -48,7 +88,7 @@ index bc034e19..929e3499 100755
  # Copy the binaries needed for code coverage and crash symbolization.
  COPY --from=base-clang /usr/local/bin/llvm-cov \
 diff --git a/projects/jackson-databind/build.sh b/projects/jackson-databind/build.sh
-index b5ea5b01..fa0001ba 100755
+index 7dd6f09b..b304a3c4 100755
 --- a/projects/jackson-databind/build.sh
 +++ b/projects/jackson-databind/build.sh
 @@ -55,6 +55,9 @@ BUILD_CLASSPATH=$(echo $ALL_JARS | xargs printf -- "$OUT/%s:"):$JAZZER_API_PATH
@@ -95,3 +135,16 @@ index b5ea5b01..fa0001ba 100755
 +cd $OUT
 +cp fuzz-introspector/frontends/java/soot/*.result ./
 +rm -rf fuzz-introspector
+diff --git a/projects/javassist/build.sh b/projects/javassist/build.sh
+index b4890d06..5c5e7fc7 100644
+--- a/projects/javassist/build.sh
++++ b/projects/javassist/build.sh
+@@ -23,7 +23,7 @@ mv ./src/test ./src/java
+ mkdir ./src/test
+ mv ./src/java ./src/test/java
+ 
+-MAVEN_ARGS="-Djavac.src.version=15 -Djavac.target.version=15 -DskipTests"
++MAVEN_ARGS="-Djavac.src.version=15 -Djavac.target.version=15 -DskipTests --quiet"
+ $MVN package org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade $MAVEN_ARGS
+ CURRENT_VERSION=$($MVN org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
+  -Dexpression=project.version -q -DforceStdout)
